# Generated by Django 5.0.2 on 2024-03-07 21:23

import recordatorios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(validators=[recordatorios.models.fecha_limite_mayor_que_hoy])),
                ('recordatorio', models.DateTimeField(validators=[recordatorios.models.fecha_limite_mayor_que_hoy])),
                ('etiqueta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(validators=[recordatorios.models.fecha_limite_mayor_que_hoy])),
                ('recordatorio', models.DateTimeField(validators=[recordatorios.models.fecha_limite_mayor_que_hoy])),
                ('etiqueta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_limite', models.DateTimeField(validators=[recordatorios.models.fecha_limite_mayor_que_hoy])),
                ('etiqueta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
