# Generated by Django 5.0.2 on 2024-03-12 21:07

import datetime
import recordatorios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='cantidad',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha',
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 16, 7, 17, 720192), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AddField(
            model_name='tarea',
            name='recordatorio',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 16, 7, 17, 720192), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 16, 7, 17, 721189), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='recordatorio',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 16, 7, 17, 721189), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='recordatorio',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 16, 7, 17, 720192), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 16, 7, 17, 720192), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
    ]
