# Generated by Django 5.0.2 on 2024-03-16 03:50

import datetime
import recordatorios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0002_rename_cantidad_pago_valor_remove_pago_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 22, 50, 24, 320894), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='recordatorio',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 22, 50, 24, 320894), validators=[recordatorios.models.fecha_recordatorio_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 22, 50, 24, 321889), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='recordatorio',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 22, 50, 24, 321889), validators=[recordatorios.models.fecha_recordatorio_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 22, 50, 24, 321889), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='recordatorio',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 22, 50, 24, 321889), validators=[recordatorios.models.fecha_recordatorio_mayor_que_hoy]),
        ),
    ]
