# Generated by Django 5.0.2 on 2024-03-16 04:14

import datetime
import recordatorios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0006_alter_evento_fecha_alter_evento_recordatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 23, 14, 30, 163356), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='recordatorio',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 23, 14, 30, 163356), validators=[recordatorios.models.fecha_recordatorio_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 23, 14, 30, 164356), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='recordatorio',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 23, 14, 30, 164356), validators=[recordatorios.models.fecha_recordatorio_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 23, 14, 30, 164356), validators=[recordatorios.models.fecha_limite_mayor_que_hoy]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='recordatorio',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 23, 14, 30, 164356), validators=[recordatorios.models.fecha_recordatorio_mayor_que_hoy]),
        ),
    ]
